### ISSUE TITLE
Code not functioning as described

### ISSUE THREAD

**Issue by SoothingMist** [punkyoon/live-graph#2]
Perhaps there is some confusion on my part.

* Downloaded the zip file.
* Opened a command console in Windows-10.
* Went to the directory containing the code.
* Used python -m venv venv (Python 3.10.1)
* Used venv\Scripts\activate to open virtual environment
* Used pip install -r requirments.txt
* Used python server.py
* Received the following error message:
(venv) D:\live-graph-master>python server.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 827-294-179
Exception in thread Thread-1 (run_server):
Traceback (most recent call last):
  File "D:\Program_Files\Python\Python3.10.1\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\Program_Files\Python\Python3.10.1\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\live-graph-master\venv\lib\site-packages\flask_socketio\__init__.py", line 603, in run_server
    addresses = eventlet.green.socket.getaddrinfo(host, port)
  File "D:\live-graph-master\venv\lib\site-packages\eventlet\support\greendns.py", line 563, in getaddrinfo
    raise socket.gaierror(socket.EAI_NONAME, 'No address found')
socket.gaierror: [Errno 11001] No address found

**Comment by SoothingMist** [comment]
Ran this same process under WSL, MS' Linux emulator on Windows 10. Received the following error message: The client is using an unsupported version of the Socket.IO or Engine.IO protocols.

**Comment by punkyoon** [comment]
Oh, I missed this issue. I apologize for that.
